import jquery from './jquery-3.6.0.min.js';
import reviews from './reviews.js';
import services from './services.js';
import work from './work.js';
import '../scss/_buy.scss';
import '../scss/_color.scss';
// import '../scss/_fonts.scss';
import '../scss/_footer.scss';
import '../scss/_header.scss';
import '../scss/_news.scss';
import '../scss/_reset.scss';
import '../scss/_reviews.scss';
import '../scss/_services.scss';
import '../scss/_work.scss';
